[project]
name = "mikrotik"
version = "0.1.0"
description = ""
authors = [
    {name = "kaggwe-marvin-wsl",email = "129196464+kaggwe-marvin@users.noreply.github.com"}
]
license = "MIT"
requires-python = ">=3.12,<3.16"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pyinstaller (>=6.22.3,<7.0.0)"
]
